BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav.yaml"
TRAINER_NAME: "ppo_"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "tb_example_t"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: 2
EVAL_CKPT_PATH_DIR: "data/example/new_checkpoints_t"
NUM_PROCESSES: 2
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/example/new_checkpoints_t"
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 500

RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    cnn_output_size: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50

    use_splitnet_auxiliary: True